# Generated by Django 5.2.11 on 2026-03-01 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerCount', models.IntegerField(default=1)),
                ('boardHeight', models.IntegerField(default=20)),
                ('gameMode', models.CharField(default='a', max_length=10)),
                ('startLevel', models.IntegerField(default=1)),
                ('gravityMode', models.CharField(default='normal', max_length=10)),
                ('manualShake', models.BooleanField(default=False)),
                ('shakeAnimation', models.BooleanField(default=False)),
                ('garbageHeight', models.IntegerField(default=0)),
                ('sparsity', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'game settings',
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('lines', models.IntegerField(default=0)),
                ('gameMode', models.CharField(default='a', max_length=10)),
                ('gravityMode', models.CharField(default='normal', max_length=10)),
                ('boardHeight', models.IntegerField(default=20)),
                ('startLevel', models.IntegerField(default=1)),
                ('garbageHeight', models.IntegerField(default=0)),
                ('sparsity', models.IntegerField(default=0)),
                ('manualShake', models.BooleanField(default=False)),
                ('replay', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controls', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user settings',
            },
        ),
    ]
